{% set name = "wsaccel" %}
{% set version = "0.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: "fdb27866bb6b6e7a29e45222778ff97938782a0ce92eff07dfb20af8fb9301c4"

build:
  number: 3
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [python_impl == "pypy"]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - cython
  run:
    - python

test:
  imports:
    - wsaccel
    - wsaccel.xormask
    - wsaccel.utf8validator

about:
  home: https://github.com/methane/wsaccel
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: WSAccell is WebSocket accelerator for AutobahnPython, and ws4py
  dev_url: https://github.com/methane/wsaccel

extra:
  recipe-maintainers:
    - synapticarbors
