schema_version: 1

context:
  name: wsaccel
  version: 0.6.6

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 18efec0a7182587ba97102b4cd8df7b4f665f45d7ca36f19783f5f081ea114ea

build:
  number: 2
  skip: python_impl == "pypy"
  script: python -m pip install . -vv --no-build-isolation --no-deps

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
  host:
    - python
    - pip
    - setuptools
    - cython
  run:
    - python

tests:
  - python:
      imports:
        - wsaccel
        - wsaccel.xormask
        - wsaccel.utf8validator
      pip_check: true

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: WSAccell is WebSocket accelerator for AutobahnPython, and ws4py
  homepage: https://github.com/methane/wsaccel
  repository: https://github.com/methane/wsaccel

extra:
  recipe-maintainers:
    - synapticarbors
